### /GET findAll
GET {{baseUrl}}:{{portNum}}/coffees HTTP/1.1

### /GET findAll with pagination query
GET {{baseUrl}}:{{portNum}}/coffees?limit=2&offset=2 HTTP/1.1

### /GET findOne
GET {{baseUrl}}:{{portNum}}/coffees/1223

### /POST create
POST {{baseUrl}}:{{portNum}}/coffees
Content-Type: application/json; charset=UTF-8

{
    "name": "yoonsang",
    "brand": "Buddy Brew",
    "flavors": [
        "vanilla",
        "cherry"
    ]
}

### /PATCH update
PATCH {{baseUrl}}:{{portNum}}/coffees/4
Content-Type: application/json; charset=UTF-8

{
    "name": "Changed!",
    "brand": "Hacked!"
}

### /DELETE delete
DELETE {{baseUrl}}:{{portNum}}/coffees/5